# fly.toml file generated for mc-server-shaine on 2022-12-08T00:46:48+08:00

app = "mc-server-shaine"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  EULA = "true"
  MEMORY = "2G"
  VERSION = "1.18.2"
  SERVER_NAME = "joogie"
  MOTD = "joogie's server for degens"
  ONLINE_MODE = "false"
  SKIP_SERVER_PROPERTIES = false
  MAX_PLAYERS = 50
  SPAWN_NPCS = false
  VIEW_DISTANCE = 12

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 25565

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 25575

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
